name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu
    steps:
      - uses: Srijan-Baniyal/Srijan-Baniyal@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
